apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest
data:
  ingest.sql: |
    INSERT INTO inventory.orders (order_date, purchaser, quantity, product_id) VALUES
    ('2017-03-05', 1004, 3, 108),
    ('2017-03-10', 1001, 1, 103),
    ('2017-03-15', 1002, 2, 109),
    ('2017-04-20', 1003, 1, 104),
    ('2017-04-25', 1004, 3, 105),
    ('2017-04-01', 1001, 1, 105),
    ('2017-05-05', 1002, 2, 101),
    ('2017-05-10', 1003, 1, 106),
    ('2017-05-15', 1004, 3, 103),
    ('2017-06-20', 1001, 1, 107),
    ('2017-06-25', 1002, 2, 103),
    ('2017-06-30', 1003, 1, 108);

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-job
spec:
  template:
    spec:
      containers:
      - name: psql
        image: governmentpaas/psql:latest
        command: ["/bin/sh", "-c"]
        args: ["psql -h postgres -U postgres -d postgres -f /tmp/ingest.sql"]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/ingest.sql
          subPath: ingest.sql
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: ingest
