---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-properties
data:
  KAFKA_NODE_ID: '1'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:9094'
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
  KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:9094'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
  KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      containers:
        - name: server
          image: apache/kafka:3.7.0
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: kafka-properties

          ports:
            - containerPort: 9092
              name: internal

            - containerPort: 9094
              name: external
          volumeMounts:
            - name: kafka-messages
              mountPath: /tmp/kafka/
      volumes:
        - name: kafka-messages
          configMap:
            name: kafka-messages
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka

  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092

    - name: external
      port: 9094
      protocol: TCP
      targetPort: 9094
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-messages
data:
  messages1.txt: |
    {"key": 1001, "value":{"id": 10001, "order_date": "2016-01-16T00:00:00+00:00", "purchaser": 1001, "quantity": 1, "product_id": 102}}
    {"key": 1002, "value":{"id": 10002, "order_date": "2016-01-17T00:00:00+00:00", "purchaser": 1002, "quantity": 2, "product_id": 105}}
    {"key": 1003, "value":{"id": 10003, "order_date": "2016-02-19T00:00:00+00:00", "purchaser": 1002, "quantity": 2, "product_id": 106}}
    {"key": 1004, "value":{"id": 10004, "order_date": "2016-02-21T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 107}}
    {"key": 1005, "value":{"id": 10005, "order_date": "2016-03-01T00:00:00+00:00", "purchaser": 1001, "quantity": 3, "product_id": 108}}
    {"key": 1006, "value":{"id": 10006, "order_date": "2016-03-05T00:00:00+00:00", "purchaser": 1004, "quantity": 2, "product_id": 109}}
    {"key": 1007, "value":{"id": 10007, "order_date": "2016-03-10T00:00:00+00:00", "purchaser": 1005, "quantity": 1, "product_id": 103}}
    {"key": 1008, "value":{"id": 10008, "order_date": "2016-03-15T00:00:00+00:00", "purchaser": 1002, "quantity": 3, "product_id": 102}}
    {"key": 1009, "value":{"id": 10009, "order_date": "2016-04-01T00:00:00+00:00", "purchaser": 1006, "quantity": 2, "product_id": 105}}
    {"key": 1010, "value":{"id": 10010, "order_date": "2016-04-05T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 103}}
    {"key": 1011, "value":{"id": 10011, "order_date": "2016-04-10T00:00:00+00:00", "purchaser": 1002, "quantity": 3, "product_id": 101}}
    {"key": 1012, "value":{"id": 10012, "order_date": "2016-04-15T00:00:00+00:00", "purchaser": 1004, "quantity": 2, "product_id": 104}}
    {"key": 1013, "value":{"id": 10013, "order_date": "2016-05-01T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 103}}
    {"key": 1014, "value":{"id": 10014, "order_date": "2016-05-21T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 107}}
    {"key": 1015, "value":{"id": 10015, "order_date": "2016-06-01T00:00:00+00:00", "purchaser": 1001, "quantity": 3, "product_id": 108}}
    {"key": 1016, "value":{"id": 10016, "order_date": "2016-06-05T00:00:00+00:00", "purchaser": 1004, "quantity": 2, "product_id": 109}}
    {"key": 1017, "value":{"id": 10017, "order_date": "2016-06-10T00:00:00+00:00", "purchaser": 1005, "quantity": 1, "product_id": 103}}
    {"key": 1018, "value":{"id": 10018, "order_date": "2016-06-15T00:00:00+00:00", "purchaser": 1002, "quantity": 3, "product_id": 102}}
    {"key": 1019, "value":{"id": 10019, "order_date": "2016-07-01T00:00:00+00:00", "purchaser": 1006, "quantity": 2, "product_id": 105}}
    {"key": 1020, "value":{"id": 10020, "order_date": "2016-07-05T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 103}}
    {"key": 1021, "value":{"id": 10021, "order_date": "2016-07-10T00:00:00+00:00", "purchaser": 1002, "quantity": 3, "product_id": 101}}
    {"key": 1022, "value":{"id": 10022, "order_date": "2016-07-15T00:00:00+00:00", "purchaser": 1004, "quantity": 2, "product_id": 104}}
    {"key": 1023, "value":{"id": 10023, "order_date": "2016-08-01T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 103}}
  messages2.txt: |
    {"key": 1024, "value":{"id": 10024, "order_date": "2017-01-16T00:00:00+00:00", "purchaser": 1001, "quantity": 1, "product_id": 102}}
    {"key": 1025, "value":{"id": 10025, "order_date": "2017-01-17T00:00:00+00:00", "purchaser": 1002, "quantity": 2, "product_id": 105}}
    {"key": 1026, "value":{"id": 10026, "order_date": "2017-02-19T00:00:00+00:00", "purchaser": 1002, "quantity": 2, "product_id": 106}}
    {"key": 1027, "value":{"id": 10027, "order_date": "2017-02-21T00:00:00+00:00", "purchaser": 1003, "quantity": 1, "product_id": 107}}
