apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
data:
  bucket.py: |
    import os, boto3
    aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
    aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")
    s3_client = boto3.client(
      "s3",
      endpoint_url=f"http://localhost:4566",
      aws_access_key_id=aws_access_key_id,
      aws_secret_access_key=aws_secret_access_key
    )
    s3_client.create_bucket(Bucket="example-postgres")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      volumes:
        - name: localstack-init
          configMap:
            name: localstack-init
            defaultMode: 0777
      containers:
        - name: localstack
          image: localstack/localstack:s3-latest
          ports:
            - name: localstack
              containerPort: 4566
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret_access_key
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: AKIAIOSFODNN7EXAMPLE
          volumeMounts:
            - name: localstack-init
              mountPath: /etc/localstack/init/ready.d
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: localstack
      port: 4566
      targetPort: 4566
  type: ClusterIP
