apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/debezium/postgres:16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  inventory.sql : |
    -- Create the schema that we'll use to populate data and watch the effect in the WAL
    CREATE SCHEMA inventory;
    SET search_path TO inventory;

    -- enable PostGis
    CREATE EXTENSION postgis;

    -- Create and populate our products using a single insert with many rows
    CREATE TABLE products (
      id SERIAL NOT NULL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description VARCHAR(512),
      weight FLOAT
    );
    ALTER SEQUENCE products_id_seq RESTART WITH 101;
    ALTER TABLE products REPLICA IDENTITY FULL;

    INSERT INTO products
    VALUES (default,'scooter','Small 2-wheel scooter',3.14),
           (default,'car battery','12V car battery',8.1),
           (default,'12-pack drill bits','12-pack of drill bits with sizes ranging from #40 to #3',0.8),
           (default,'hammer','12oz carpenter''s hammer',0.75),
           (default,'hammer','14oz carpenter''s hammer',0.875),
           (default,'hammer','16oz carpenter''s hammer',1.0),
           (default,'rocks','box of assorted rocks',5.3),
           (default,'jacket','water resistent black wind breaker',0.1),
           (default,'spare tire','24 inch spare tire',22.2);

    -- Create and populate the products on hand using multiple inserts
    CREATE TABLE products_on_hand (
      product_id INTEGER NOT NULL PRIMARY KEY,
      quantity INTEGER NOT NULL,
      FOREIGN KEY (product_id) REFERENCES products(id)
    );
    ALTER TABLE products_on_hand REPLICA IDENTITY FULL;

    INSERT INTO products_on_hand VALUES (101,3);
    INSERT INTO products_on_hand VALUES (102,8);
    INSERT INTO products_on_hand VALUES (103,18);
    INSERT INTO products_on_hand VALUES (104,4);
    INSERT INTO products_on_hand VALUES (105,5);
    INSERT INTO products_on_hand VALUES (106,0);
    INSERT INTO products_on_hand VALUES (107,44);
    INSERT INTO products_on_hand VALUES (108,2);
    INSERT INTO products_on_hand VALUES (109,5);

    -- Create some customers ...
    CREATE TABLE customers (
      id SERIAL NOT NULL PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE
    );
    ALTER SEQUENCE customers_id_seq RESTART WITH 1001;
    ALTER TABLE customers REPLICA IDENTITY FULL;

    INSERT INTO customers
    VALUES (default,'Sally','Thomas','sally.thomas@acme.com'),
           (default,'George','Bailey','gbailey@foobar.com'),
           (default,'Edward','Walker','ed@walker.com'),
           (default,'Anne','Kretchmar','annek@noanswer.org'),
           (default,'John','Smith','jsmith@foobar.com'),
           (default,'Ellen','Parker','Ellen.parker@noanswer.org');

    -- Create table with Spatial/Geometry type
    CREATE TABLE geom (
            id SERIAL NOT NULL PRIMARY KEY,
            g GEOMETRY NOT NULL,
            h GEOMETRY);

    INSERT INTO geom
    VALUES(default, ST_GeomFromText('POINT(1 1)')),
          (default, ST_GeomFromText('LINESTRING(2 1, 6 6)')),
          (default, ST_GeomFromText('POLYGON((0 5, 2 5, 2 7, 0 7, 0 5))'));
